### ISSUE TITLE
Supporting scaled similarity

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#73]
Comments from @PaulWAyers 

Similarity and scaled similarity (S(i,j)/SQRT(S(i,i)S(j,j))
 5 different methods for computing dissimilarity
One of these five (or not?) should be S(i,i) + S(j,j)- 2S(i,j) where S(i,j) is the similarity. This is the distance via a covariance matrix and is important in Gaussian processes.

One can also consider S(i,j)/SQRT(S(i,i)S(j,j)) and compute the distance-squared from that. That's a correlation matrix/distance.

**Comment by fwmeng88** [comment]
For now, in order to support the implementation to compute distance, it's required to have two arguments for the distance matrix. For example, https://github.com/theochem/DiverseSelector/blob/e18651a849992e0cda2b3fe31d0ec0c07629ea1c/DiverseSelector/distance.py#L120-#L148. But in order to support scaled similarity, the easiest way of doing it to add another argument to turn this scaled similarity on and off. But this makes it incompatible with the usage of `pairwise_distance()` in `scikit-learn`.

Do you have some ideas on how to make it work?  Thank you. @PaulWAyers @FarnazH @RichRick1 @alnaba1

**Comment by PaulWAyers** [comment]
Is there a reference for the 5 ways of computing similarity that was in the original issue?

**Comment by fwmeng88** [comment]
Actually, that are 7 ways of computing dissimilarity or diversity. 

1. total diversity column, Eq. 4 on page 843 of [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci9700337) (the first method in this paper)
2. Eq. 9 on page 844 of [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci9700337) (the second method in this paper)
3. Gini coefficient from [Journal of Computational Chemistry2016,37, 2091–2097](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24423)
4. entropy from Eq. 9 on page 4 of [Leguy et al. J Cheminform (2021) 13:76](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00554-8) with implementation at https://github.com/jules-leguy/EvoMol/blob/master/evomol/evaluation_entropy.py
5. log-determinant function from [Sci. Rep. 12: 1124 (2022)](https://www.nature.com/articles/s41598-022-04967-9)
6. Wasserstein distance for property‑based evaluation of diversity. from [Sci. Rep. 12: 1124 (2022)](https://www.nature.com/articles/s41598-022-04967-9) with codes available at https://github.com/tomotomonakanaka/SUBMO
7. Explicit Diversity Index from [J. Chem. Inf. Model. 2006, 46, 5, 1898–1904](https://pubs.acs.org/doi/10.1021/ci060074f)

I think they all have been implemented.

**Comment by PaulWAyers** [comment]
I thought this referred to ways to take distance to/from similarity. So there was
distance(i,j) = S(i,i) + S(j,j) - 2 S(i,j) 
which corresponds (some information is missing now so one needs to assume something like S(i,i) = 1) to
S(i,j) = 1/2 (1 - d(i,j)) (i /= j)
S(i,i) = 1    (just a choice for convenience).

There is also a diversity measure direction from determinantal point processes. For feature vectors/bitstrings I think (@Ali-Tehrani am I right about this) it is the determinant of the Gramian; for distance/similarity matrices it would be the determinant of the similarity matrix.

**Comment by Ali-Tehrani** [comment]
Feature Vectors
----------------------
The feature matrix may not be square and so the determinant wouldn't be defined.  What you could do instead is to take the norm of the exterior product of the [columns](https://en.wikipedia.org/wiki/Parallelepiped#Parallelotope) which is equivalent to calculating the Gramian and taking it's [determinant](https://en.wikipedia.org/wiki/Gram_matrix#Gram_determinant).   The determinant can also be taken from a reference point,

If the Gramian is not positive definite, then the determinant would be zero and so you could instead take the non-zero eigenvalues and multiply them together.   Not sure how else to do this other than doing a Gaussian elimination to find the bases for the column space and taking the determinant of that Gramian matrix.

So, taking the determinant of the Gramian of the entire feature matrix can be done but computationally expensive.

Similarity Function
-------------------------
If the similarity function isn't an inner-product (not every norm corresponds to a inner-product needs to satisfy the parallelogram law), then the determinant can be negative and so you'll need to take the absolute value of it.  
It's hard for me to imagine if the geometric intuition even makes sense in such a case, because looking at the [norm of the exterior product](https://en.wikipedia.org/wiki/Gram_matrix#Gram_determinant) it seems to imply that S(., .) is atleast bi-linear and split under tensor-products.

Also, the sampling procedure for DPP won't work as it assumes the similarity matrix is at-least positive semidefinite.  

So, I don't think the absolute value of determinant as a measure of diversity for any similarity function is fine without some assumptions.

**Comment by PaulWAyers** [comment]
In response to @Ali-Tehrani 
1. I think taking a product of the nonzero eigenvalues of the Gramian (or perhaps all the eigenvalues above a threshhold) is sensible. When the feature vector is shorter than the number of molecules, there will of course be a lot of zero eigenvalues. I don't know a great mathematical justification, but intuitively the p-norm of the singular values of the feature matrix should also indicate diversity (more is better). The 1-norm (nuclear norm) is an effective rank of the feature matrix.  (Note that the eigenvalues of the Gramian are exactly the singular values. I think the p->0 quasinorm may be the determinant.

2. I agree that the absolute value of the determinant isn't an "assumptionless" measure of diversity but I think it can still be useful, though assumptions need to be clearly stated. Ditto for the deteminantal point process, I think.

**Comment by PaulWAyers** [comment]
I think the similarity/distance conversions I had in mind were from:
https://rdrr.io/cran/smacof/man/sim2diss.html

**Comment by FanwangMeng** [comment]
> I think the similarity/distance conversions I had in mind were from: https://rdrr.io/cran/smacof/man/sim2diss.html

I got a question with the `ranking` method listed here. In their implementation (https://rdrr.io/cran/smacof/src/R/sim2diss.R), the `rank` function (https://rdrr.io/r/base/rank.html) is used. But I don't understand what is about and I was not able to find more related literature online. Can you help provide the math details? Thank you. @PaulWAyers 

Here is some play around with this function.
```R
> test
         BRAZIL CONGO  CUBA EGYPT FRANCE INDIA ISRAEL JAPAN CHINA RUSSIA   USA
CONGO      35.5                                                               
CUBA       19.5  49.5                                                         
EGYPT     106.5  30.5  21.5                                                   
FRANCE     42.5  85.5  77.5  39.5                                             
INDIA      53.5  35.5  85.5   9.5  106.5                                      
ISRAEL     92.5 114.5  97.5  45.5   85.5  77.5                                
JAPAN     102.5 110.5 125.5  92.5   69.5  53.5   35.5                         
CHINA     130.5  85.5  13.5  60.5   95.5  77.5  123.5  72.5                   
RUSSIA    121.5 110.5  15.5  60.5   26.5  53.5   72.5  47.5  11.5             
USA        17.5 130.5 118.5 114.5    6.5  65.5    6.5   3.5 127.5   30.5      
YUGOSLAV  118.5 102.5  23.5  65.5   42.5  85.5   57.5  65.5  26.5    1.5  99.5

> rank(-wish)
  BRAZIL    CONGO     CUBA    EGYPT   FRANCE    INDIA   ISRAEL    JAPAN    CHINA 
    18.0     10.0     53.5     21.5     27.0     46.5     51.5     65.5     61.0 
  RUSSIA      USA YUGOSLAV     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
     9.0     59.5     25.0     15.5     43.0     18.0     57.5     55.5     43.0 
    <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
    55.5     65.5     51.5     11.0     39.0     43.0     49.0     63.0      7.0 
    <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
     8.0     59.5     12.0     20.0      5.0     23.0     46.5     30.5     30.5 
    <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
    57.5     33.0     53.5     43.0     35.0     48.0     13.5      3.5     21.5 
    <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
    39.0     27.0     39.0     27.0     33.0     43.0     18.0     62.0     36.5 
    <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA>     <NA> 
     3.5     29.0     36.5     24.0      2.0     33.0      6.0     64.0     13.5 
    <NA>     <NA>     <NA> 
    15.5      1.0     50.0 

> sim2diss(wish, method="rank", to.dist = TRUE)
         BRAZIL CONGO  CUBA EGYPT FRANCE INDIA ISRAEL JAPAN CHINA RUSSIA   USA
CONGO      35.5                                                               
CUBA       19.5  49.5                                                         
EGYPT     106.5  30.5  21.5                                                   
FRANCE     42.5  85.5  77.5  39.5                                             
INDIA      53.5  35.5  85.5   9.5  106.5                                      
ISRAEL     92.5 114.5  97.5  45.5   85.5  77.5                                
JAPAN     102.5 110.5 125.5  92.5   69.5  53.5   35.5                         
CHINA     130.5  85.5  13.5  60.5   95.5  77.5  123.5  72.5                   
RUSSIA    121.5 110.5  15.5  60.5   26.5  53.5   72.5  47.5  11.5             
USA        17.5 130.5 118.5 114.5    6.5  65.5    6.5   3.5 127.5   30.5      
YUGOSLAV  118.5 102.5  23.5  65.5   42.5  85.5   57.5  65.5  26.5    1.5  99.5

```

**Comment by PaulWAyers** [comment]
@FanwangM and I decided not to implement the ranking (dis)similarity method.

**Comment by FanwangM** [comment]
Suppressed by #73.
